#ifndef C02CDB99_AA83_45B0_83E7_8C8BC254A8A2
#define C02CDB99_AA83_45B0_83E7_8C8BC254A8A2

#include "login_matchmaking_game_shared/gameOptionAsString.hxx"
#include <cstddef>

BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinChannel, (std::string, channel))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinChannelSuccess, (std::string, channel))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinChannelError, (std::string, channel) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateAccount, (std::string, accountName) (std::string, password))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateAccountCancel, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateAccountSuccess, (std::string, accountName))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateAccountError, (std::string, accountName) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAccount, (std::string, accountName) (std::string, password))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAccountCancel, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAccountSuccess, (std::string, accountName))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAccountError, (std::string, accountName) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LogoutAccount, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LogoutAccountSuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LogoutAccountError, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), BroadCastMessage, (std::string, channel) (std::string, message))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), BroadCastMessageSuccess, (std::string, channel) (std::string, message))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), BroadCastMessageError, (std::string, channel) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveChannel, (std::string, channel))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveChannelSuccess, (std::string, channel))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveChannelError, (std::string, channel) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), Message, (std::string, fromAccount) (std::string, channel) (std::string, message))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateGameLobby, (std::string, name) (std::string, password))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateGameLobbySuccess, (std::string, name))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateGameLobbyError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinGameLobby, (std::string, name) (std::string, password))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinGameLobbySuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinGameLobbyError, (std::string, name) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GameOptionError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UserInGameLobby, (std::string, accountName))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UsersInGameLobby, (std::string, name) (std::vector<user_matchmaking::UserInGameLobby>, users) (size_t, maxUserSize) (user_matchmaking_game::GameOptionAsString, gameOptionAsString))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), SetMaxUserSizeInCreateGameLobby, (size_t, maxUserSize))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), SetMaxUserSizeInCreateGameLobbyError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), MaxUserSizeInCreateGameLobby, (size_t, maxUserSize))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveGameLobby, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveGameLobbySuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveGameLobbyError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), WantToRelog, (std::string, accountName) (std::string, destination))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RelogTo, (bool, wantsToRelog))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RelogToCreateGameLobbySuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RelogToGameSuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RelogToError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateGame, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), CreateGameError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), StartGame, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), StartGameError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinMatchMakingQueue, (bool, isRanked))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinMatchMakingQueueSuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), JoinMatchMakingQueueError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), AskIfUserWantsToJoinGame, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), AskIfUserWantsToJoinGameTimeOut, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GameStartCanceled, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GameStartCanceledRemovedFromQueue, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), WantsToJoinGame, (bool, answer))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), WantsToJoinGameError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveQuickGameQueue, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveQuickGameQueueSuccess, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LeaveQuickGameQueueError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAsGuest, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoginAsGuestSuccess, (std::string, accountName))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RatingChanged, (size_t, oldRating) (size_t, newRating))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UnhandledMessageError, (std::string, msg) (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), ProxyStarted, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), ProxyStopped, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), ConnectGameError, (std::string, error))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UnhandledEventError, (std::string, unhandledEvent) (std::string, reason))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GetMatchmakingLogic, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), MatchmakingLogic, (std::string, logic))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GetUserStatistics, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UserStatistics, (size_t, userInCreateCustomGameLobby) (size_t, userInUnRankedQueue) (size_t, userInRankedQueue) (size_t, userInGame))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GetTopRatedPlayers, (size_t, playerCount))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), RatedPlayer, (std::string, name) (size_t, rating))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), TopRatedPlayers, (std::vector<user_matchmaking::RatedPlayer>, players))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), SubscribeGetTopRatedPlayers, (uint64_t, playerCount))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), UnSubscribeGetTopRatedPlayers, )
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), GetLoggedInPlayers, (uint64_t, playerCount))
BOOST_FUSION_DEFINE_STRUCT ((user_matchmaking), LoggedInPlayers, (std::vector<std::string>, players))
#endif /* C02CDB99_AA83_45B0_83E7_8C8BC254A8A2 */
